# Workflow to associate labels automatically
name: labeler
# Trigger the workflow on pull request events
on: 
  issues:
    types:
      - opened
      - reopened
  pull_request:
    branches: "*"

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      # We need to checkout the repository to access the configured file (.github/label-pr.yml)
      - uses: actions/checkout@v2
      - name: Labeler
        uses: actions/labeler@v4.0.3
        with:
          # The GitHub token used to manage labels
          repo-token: ${{ secrets.GITHUB_TOKEN }}
